name: CI-CD_Pipeline
env:
  EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flasck-application-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIROMENT_NAME        : "My-Flask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"
  
on:
  push:
    branches:
      -master

jobs:
  my_ci_part:
     runs-on: ubuntu-latest
     
     steps: 
     - name: Git clone our repo
       users: acrions/checkout@v1
       
     - name: Create ZIP deployment package
       run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x "*.git*"

     



      
